# Basic Command Note
### import

In [5]:
import numpy as np

In [4]:
keras.__version__

'2.2.4'

## Nomal Python
### basic technique

In [37]:
x = 'learning'
print(type(x))
print(x)

<class 'str'>
learning


In [10]:
x = 1 / 3
y = 1 / 7
z = 1 / 4
print('weight: = {0}kg, {1}kg, {2}kg'.format(x, y, z))
print('weight: = {1}kg, {2}kg, {1}kg'.format(x, y, z))
print('weight: = {0}kg, {2}kg, {1}kg'.format(x, x, x))
print('weight: = {0:.2f}kg, {1:.2f}kg, {2:.2f}kg'.format(x, y, z))

weight: = 0.3333333333333333kg, 0.14285714285714285kg, 0.25kg
weight: = 0.14285714285714285kg, 0.25kg, 0.14285714285714285kg
weight: = 0.3333333333333333kg, 0.3333333333333333kg, 0.3333333333333333kg
weight: = 0.33kg, 0.14kg, 0.25kg
weight: = 0.3333333333333333kg, 0.3333333333333333kg, 0.3333333333333333kg


### array

In [7]:
x = [1, 1, 2, 3, 5]
print(x)
print(x[0])
print(x[2])
print(type(x))
print(type(x[0]))
s=['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))

[1, 1, 2, 3, 5]
1
2
<class 'list'>
<class 'int'>
<class 'str'>
<class 'int'>


In [8]:
a=[[1, 2, 3], [4, 5, 6]]
print(a)
print(a[0][1])
print(len(a))
print(len(a[0]))

[[1, 2, 3], [4, 5, 6]]
2
2
3


### range

In [36]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])
print(y)
z=list(range(5, 10))
print(z)
print(list(range(10)))

5 6 7 8 9
range(5, 10)
[5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### tuple

In [10]:
a=(1, 2, 3)#Can't edit
print(a)
print(a[1])
print(type(a))
a=(1)
print(type(a))
a=(1,)
print(type(a))

(1, 2, 3)
2
<class 'tuple'>
<class 'int'>
<class 'tuple'>


### conditional branching

In [11]:
x = 11
print(x > 10)
print(type(x > 10))
if x > 10:
    print('x is')
    print('    larget than 10.')
else:
    print('x is smaller than 11')

x = 15
if 10 <= x and x <= 20:
    print('x is between 10 and 20.')

True
<class 'bool'>
x is
    larget than 10.
x is between 10 and 20.


### repetition

In [12]:
for i in [1, 2, 3]:
    print(i)
    
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)
num = [2, 4, 6, 8, 10]        
for i, n in enumerate(num):
    num[i] = n * 2
print(num)

1
2
3
[4, 8, 12, 16, 20]
[4, 8, 12, 16, 20]


### normal tensor connection

In [13]:
[1,2]+[3,4]

[1, 2, 3, 4]

## NumPy Basic
### array

In [14]:
x=np.array([1, 2, 3])
print(x)
x

[1 2 3]


array([1, 2, 3])

### arithmetic operations

In [15]:
y=np.array([4, 5, 6])
print(x+y)
print(type(x))
print(x[0])
x[0] = 100
print(x)

[5 7 9]
<class 'numpy.ndarray'>
1
[100   2   3]


### important point

In [16]:
example=np.arange(100)#! range
example=example.reshape(10, 10)#Don"t forget substitution
print(example)

print(np.arange(10))
print(np.arange(5, 10))
a = np.array([1, 1])#a array = b array
b=a
c=a.copy()
print('a =' + str(a))
print('b =' + str(b))
print('c =' + str(c))
b[0]=100
print('a =' + str(a))
print('b =' + str(b))
print('c =' + str(c))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
a =[1 1]
b =[1 1]
c =[1 1]
a =[100   1]
b =[100   1]
c =[1 1]


### multidimensional array

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)
w, h = x.shape
print(w)
print(h)
print(x[1,2])
x[1, 2] = 100
print(x)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
3
6
[[  1   2   3]
 [  4   5 100]]


### array generation function

In [18]:
print(np.zeros(10))#size = tuple
print(np.zeros((2, 10)))
print(np.ones((2, 10)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [20]:
print(np.random.rand(2, 3))#!=np.random.rand((2, 3))  
print(np.random.randn(2, 3))#Gaussian
print(np.random.randint(-10, 100, (2, 10)))

[[0.18386369 0.26172226 0.79837664]
 [0.81722869 0.07636378 0.03833413]]
[[-0.23631251  0.91175002  0.20397099]
 [-0.63657999 -1.02864009 -0.64225511]]
[[90  6 51  2 28 55 81 98 57 92]
 [96 -8 -1 46 46 33 61 -6 76  2]]


### reshape

In [28]:
a = np.arange(10)
print(a)
a.reshape(2, 5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### array operation

In [29]:
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)
print(10 * x)
print(np.exp(x))
print(np.log(x))
print(np.std(x))

[[ 5  5  5]
 [10 10 10]]
[[40 40 40]
 [80 80 80]]
[[  54.59815003   54.59815003   54.59815003]
 [2980.95798704 2980.95798704 2980.95798704]]
[[1.38629436 1.38629436 1.38629436]
 [2.07944154 2.07944154 2.07944154]]
2.0


In [30]:
v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1], [2, 2], [3, 3]])
print(v.dot(w))

[[14 14]
 [32 32]]


### slicing

In [52]:
x = np.arange(10)
print(x)
print(x[:5])
print(x[5:])
print(x[3:8])
print(x[3:8:2])
print(x[::-1])
y = np.arange(100)
y = y.reshape(10, 10)
print(y)
print(y[:4, 1:6])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[3 4 5 6 7]
[3 5 7]
[9 8 7 6 5 4 3 2 1 0]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]]


### bool array

In [54]:
x=np.array([1, 1, 2, 3, 5, 8, 13])
print(x > 3)
print(x[x > 3])
x[x > 3] = 999
print(x)

[False False False False  True  True  True]
[ 5  8 13]
[  1   1   2   3 999 999 999]


### help function

In [55]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

### function

In [6]:
def my_func1(): #def = define
    print('Hi!')
#end
my_func1()

def my_func2(a, b):
    c = a + b
    return c

print(my_func2(1, 2))

def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s
data = np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean, data_std))
output = my_func3(data)
print(output)
print(type(output))
print('mean:{0:3.2f}, std:{1:3.2f}'.format(output[0], output[1]))

Hi!
3
mean:0.02, std:1.04
(0.020177736020707382, 1.0436816459816511)
<class 'tuple'>
mean:0.02, std1.04


### file

In [9]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy', data)
data = []
print(data)
data = np.load('datafile.npy')
print(data)

data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
np.savez('datafile2.npz', data1=data1, data2=data2)
data1 = []
data2 = []
outfile = np.load('datafile2.npz')
print(outfile.files)
data1 = outfile['data1']
data2 = outfile['data2']
print(data1)
print(data2)

[-0.59398678  0.0677462  -0.53588336  1.25832235 -0.51403728]
[]
[-0.59398678  0.0677462  -0.53588336  1.25832235 -0.51403728]
['data1', 'data2']
[1 2 3]
[10 20 30]
