# Basic TensorFlow 
### import

In [1]:
import tensorflow as tf
tf.__version__

'1.5.0'

## Data Graph System
### add

In [2]:
tf.reset_default_graph()#dataGraphResetCommand--------------------------------------
a = tf.constant(1, name='a')
b = tf.constant(1, name='b')
c = a + b
with tf.Session() as sess:
    print(sess.run(c))
print(c)
graph = tf.get_default_graph()
print(graph.as_graph_def())

2
Tensor("add:0", shape=(), dtype=int32)
node {
  name: "a"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "b"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "a"
  input: "b"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
versions {
  producer: 24
}



### Variable

In [3]:
a = tf.Variable(1, name='a')
b = tf.constant(1, name='b')
c = tf.assign(a, a+b)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('一回目:[c, a]=', sess.run([c, a]))
    print('二回目:[c, a]=', sess.run([c, a]))

一回目:[c, a]= [2, 2]
二回目:[c, a]= [3, 3]


### Placeholder

In [4]:
a = tf.placeholder(dtype=tf.int32, name='a')
b = tf.constant(1, name='b')
c = a + b

with tf.Session() as sess:
    print('a + b =', sess.run(c, feed_dict={a: 1}))

a + b = 2


### Arithmatic Operation

In [5]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
c = tf.add(a, b)# = a + b
d = tf.multiply(a, b)# = a * b
with tf.Session() as sess:
    print('a + b = ', sess.run(c))
    print('a * b = ', sess.run(d))

a + b =  5
a * b =  6


### Vector

In [6]:
a = tf.constant([1, 2, 3], name='a')
b = tf.constant([4, 5, 6], name='b')
c = a + b

with tf.Session() as sess:
    print('a + b = ', sess.run(c))

a + b =  [5 7 9]


### Matrix

In [22]:
a = tf.constant([[1, 2], [3, 4]], name='a')
b = tf.constant([[1], [2]], name='b')
c = tf.matmul(a, b)

print('shape of a:', a.shape)
print('shape of b:', b.shape)
print('shape of c:', c.shape)

with tf.Session() as sess:
    print('a = \n', sess.run(a))
    print('b = \n', sess.run(b))
    print('c = \n', sess.run(c))

shape of a: (2, 2)
shape of b: (2, 1)
shape of c: (2, 1)
a = 
 [[1 2]
 [3 4]]
b = 
 [[1]
 [2]]
c = 
 [[ 5]
 [11]]
