# Vector
### import

In [2]:
import numpy as np

## basic

In [4]:
a = np.array([2, 1])
print(a)
print(type(a))
c = np.array([[1, 2], [3, 4]])
print(c)
d = np.array([[1], [2]])
print(d)

[2 1]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
[[1]
 [2]]


### transposition

In [3]:
d = np.array([[1, 2, 3], [4, 5, 6]])
print(d)
print(d.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### atithmetic operations

In [11]:
a = np.array([2, 1])
b = np.array([1, 3])
c = np.array([4, 2])
print(a + b)
print(a - b)
print(2 * a)
print(b.dot(c)) #inner product
print(np.linalg.norm(a)) #vector size

[3 4]
[ 1 -2]
[4 2]
10
2.23606797749979


### speed calculation

In [10]:
a = np.ones(1000)
b = np.arange(1, 1001)
print(a.dot(b)) #speedy

500500.0


# 